[package]
name = "critters-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
itertools = "0.13.0"
kuchikiki = "0.8.2"
lightningcss = "1.0.0-alpha.59"
log = "0.4.22"
markup5ever = "0.11.0"
regex = "1.10.6"
