//! Shared loading logic for the real-world snapshot tests and benchmarks.
//!
//! `include!`d as a module by both `tests/real_world.rs` and
//! `benches/real_world.rs`. Each site's fixtures live in
//! `test_files/<name>/`, generated by `scripts/fetch-real-world.ts`.

use critters_rs::{Critters, CrittersOptions};
use std::{fs, path::PathBuf};

/// Load a real-world site fixture, returning a configured `Critters` instance
/// and the page's HTML.
pub fn load(name: &str) -> (Critters, String) {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("test_files")
        .join(name);
    let html = fs::read_to_string(dir.join("index.html"))
        .unwrap_or_else(|e| panic!("failed to read {}/index.html: {e}", dir.display()));
    let critters = Critters::new(CrittersOptions {
        path: dir.to_string_lossy().to_string(),
        external: true,
        ..Default::default()
    });
    (critters, html)
}
