// @generated by scripts/fetch-real-world.ts from test_files/manifest.jsonc
// Do not edit by hand. Run `pnpm benchmarks:fetch` to regenerate.
real_world_sites! {
    html_standard,
    michaelt_xyz,
    rust_wikipedia,
    time_mag,
    wikipedia_2020s,
    wikipedia_japanese_conjugation,
}
